image: atlassian/default-image:2
pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - apt-get update && apt-get install -y blender libav-tools ffmpeg
          - mkdir $HOME/tmp/
          - ./example.sh test01.blend
