# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.5
    - name: Install dependencies
      run: |
        sudo apt-get install -y blender ffmpeg
    - name: Test script execution
      env: 
        BLENDERER: /home/runner/work/blenderer.py
      run: |
        mkdir $HOME/tmp/
        ./example.sh test01.blend
    - name: Unit tests
      run: python3 blenderer_test.py
